//! Route authorization inventory for the first AuthorizationPolicy slice (#710).
//!
//! This table is intentionally executable: authentication exemptions and
//! admin/operator checks read from it, and tests compare it with the Axum router
//! declarations in `main.rs`. The first slice keeps enforcement coarse while
//! making every externally registered route carry policy/docs/cache metadata.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyClass {
    Public,
    PublicWithInlineProof,
    AuthenticatedRead,
    AuthenticatedWrite,
    AdminOperator,
    TenantObject,
    SystemHealth,
    Docs,
    OAuth,
    RealtimeTransport,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DocsExposureClass {
    Public,
    Authenticated,
    Operator,
    Hidden,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CacheHeaderClass {
    PublicStatic,
    PublicProbe,
    PrivateUserData,
    NoStore,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RoutePolicy {
    pub path: &'static str,
    pub class: PolicyClass,
    pub action_family: &'static str,
    pub docs: DocsExposureClass,
    pub cache: CacheHeaderClass,
}

use CacheHeaderClass::*;
use DocsExposureClass::{Authenticated, Hidden, Operator, Public as DocsPublic};
use PolicyClass::{
    AdminOperator, AuthenticatedRead, AuthenticatedWrite, Docs, OAuth, Public,
    PublicWithInlineProof, RealtimeTransport, SystemHealth, TenantObject,
};

pub const ROUTE_POLICY_INVENTORY: &[RoutePolicy] = &[
    r(
        "/.well-known/oauth-authorization-server",
        OAuth,
        "oauth_discovery",
        DocsPublic,
        PublicProbe,
    ),
    r(
        "/.well-known/oauth-protected-resource",
        OAuth,
        "oauth_discovery",
        DocsPublic,
        PublicProbe,
    ),
    r(
        "/api/v1/api-keys",
        AdminOperator,
        "credential_management",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/api-keys/{id}",
        AdminOperator,
        "credential_management",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/archives",
        AdminOperator,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/archives/{name}",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/archives/{name}/clone",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/archives/{name}/set-default",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/archives/{name}/stats",
        AuthenticatedRead,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/attachments",
        TenantObject,
        "attachment",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/attachments/{attachment_id}",
        TenantObject,
        "attachment",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/attachments/{attachment_id}/download",
        TenantObject,
        "attachment",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/attachments/{attachment_id}/sprites/{sprite_index}",
        TenantObject,
        "attachment",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/attachments/{attachment_id}/subtitles",
        TenantObject,
        "attachment",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/attachments/{attachment_id}/thumbnail",
        TenantObject,
        "attachment",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/attachments/{attachment_id}/thumbnails.vtt",
        TenantObject,
        "attachment",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/audio/transcribe",
        AuthenticatedWrite,
        "ai_execution",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/backup/database",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/database/restore",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/database/snapshot",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/database/upload",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/download",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/export",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/import",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/knowledge-archive",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/knowledge-archive/{filename}",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/knowledge-shard",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/knowledge-shard/import",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/knowledge-shard/upload",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/list",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/list/{filename}",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/memory/{name}",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/metadata/{filename}",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/status",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/swap",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/backup/trigger",
        AdminOperator,
        "backup_restore",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/calls/{id}",
        TenantObject,
        "realtime_call",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/chat",
        AuthenticatedWrite,
        "ai_execution",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/chat/models",
        AuthenticatedRead,
        "ai_execution",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/chat/stream",
        AuthenticatedWrite,
        "ai_execution",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/collections",
        TenantObject,
        "collection",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/collections/{id}",
        TenantObject,
        "collection",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/collections/{id}/export",
        TenantObject,
        "collection",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/collections/{id}/notes",
        TenantObject,
        "collection",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/autocomplete",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/collections",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/collections/{id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/collections/{id}/members",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/collections/{id}/members/{concept_id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/governance",
        AdminOperator,
        "taxonomy",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/concepts/schemes",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/schemes/export/turtle",
        TenantObject,
        "taxonomy",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/concepts/schemes/{id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/schemes/{id}/export/turtle",
        TenantObject,
        "taxonomy",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/concepts/schemes/{id}/top-concepts",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/ancestors",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/broader",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/broader/{target_id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/descendants",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/full",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/narrower",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/narrower/{target_id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/related",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/concepts/{id}/related/{target_id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/document-types",
        AdminOperator,
        "document_type_catalog",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/document-types/detect",
        AuthenticatedWrite,
        "document_type_catalog",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/document-types/{name}",
        AdminOperator,
        "document_type_catalog",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/embedding-configs",
        AdminOperator,
        "embedding_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/embedding-configs/default",
        AdminOperator,
        "embedding_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/embedding-configs/{id}",
        AdminOperator,
        "embedding_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/embedding-sets",
        TenantObject,
        "embedding_control",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/embedding-sets/{slug}",
        TenantObject,
        "embedding_control",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/embedding-sets/{slug}/members",
        TenantObject,
        "embedding_control",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/embedding-sets/{slug}/members/{note_id}",
        TenantObject,
        "embedding_control",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/embedding-sets/{slug}/refresh",
        TenantObject,
        "embedding_control",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/events",
        RealtimeTransport,
        "event_stream",
        Hidden,
        NoStore,
    ),
    r(
        "/api/v1/extraction/stats",
        AdminOperator,
        "system_diagnostics",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/cold-spots",
        TenantObject,
        "graph_control",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/graph/community/coarse",
        TenantObject,
        "graph_control",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/graph/diagnostics",
        AdminOperator,
        "graph_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/diagnostics/compare",
        AdminOperator,
        "graph_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/diagnostics/history",
        AdminOperator,
        "graph_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/diagnostics/snapshot",
        AdminOperator,
        "graph_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/maintenance",
        AdminOperator,
        "graph_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/pfnet/sparsify",
        AdminOperator,
        "graph_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/snn/recompute",
        AdminOperator,
        "graph_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/graph/topology/stats",
        AuthenticatedRead,
        "graph_control",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/graph/{id}",
        TenantObject,
        "graph_control",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/health/access-frequency",
        SystemHealth,
        "health_diagnostics",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/health/knowledge",
        SystemHealth,
        "health_diagnostics",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/health/orphan-tags",
        SystemHealth,
        "health_diagnostics",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/health/stale-notes",
        SystemHealth,
        "health_diagnostics",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/health/streaming",
        SystemHealth,
        "health_diagnostics",
        DocsPublic,
        PublicProbe,
    ),
    r(
        "/api/v1/health/tag-cooccurrence",
        SystemHealth,
        "health_diagnostics",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/health/unlinked-notes",
        SystemHealth,
        "health_diagnostics",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/inbound-sources",
        AdminOperator,
        "inbound_connector",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/inbound-sources/{name}",
        AdminOperator,
        "inbound_connector",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/inference/complete",
        AuthenticatedWrite,
        "ai_execution",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/inference/config",
        AdminOperator,
        "model_config",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/inference/config/audit",
        AdminOperator,
        "model_config",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/inference/providers",
        AuthenticatedRead,
        "ai_execution",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/inference/stream",
        AuthenticatedWrite,
        "ai_execution",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/inference/test-connection",
        AdminOperator,
        "model_config",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/ingest/stream",
        RealtimeTransport,
        "ingest_stream",
        Hidden,
        NoStore,
    ),
    r(
        "/api/v1/ingest/tokens",
        AdminOperator,
        "ingest_stream",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/ingest/tokens/{token_id}",
        AdminOperator,
        "ingest_stream",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/pause",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/pause/{archive}",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/pending",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/resume",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/resume/{archive}",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/stats",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/status",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/jobs/{id}",
        AdminOperator,
        "job_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/memories",
        AdminOperator,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/memories/overview",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/memories/search",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/memories/{name}",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/memories/{name}/clone",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/memories/{name}/set-default",
        TenantObject,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/memories/{name}/stats",
        AuthenticatedRead,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/memory/info",
        AuthenticatedRead,
        "memory_management",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/models",
        AuthenticatedRead,
        "model_catalog",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/activity",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/bulk",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/reprocess",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/timeline",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/attachments",
        TenantObject,
        "attachment",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/attachments/tus",
        TenantObject,
        "attachment",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/attachments/tus/{upload_id}",
        TenantObject,
        "attachment",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/attachments/upload",
        TenantObject,
        "attachment",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/backlinks",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/concepts",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/concepts/{concept_id}",
        TenantObject,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/export",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/full",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/links",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/memory-provenance",
        TenantObject,
        "provenance",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/move",
        TenantObject,
        "collection",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/provenance",
        TenantObject,
        "provenance",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/purge",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/related",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/reprocess",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/restore",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/status",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/notes/{id}/tags",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/versions",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/versions/diff",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/versions/{version}",
        TenantObject,
        "note",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/notes/{id}/versions/{version}/restore",
        TenantObject,
        "note",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/pke/address",
        AuthenticatedWrite,
        "pke",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/pke/decrypt",
        AuthenticatedWrite,
        "pke",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/pke/encrypt",
        AuthenticatedWrite,
        "pke",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/pke/keygen",
        AuthenticatedWrite,
        "pke",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/pke/keysets",
        AdminOperator,
        "pke_keyset",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/pke/keysets/active",
        AdminOperator,
        "pke_keyset",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/pke/keysets/import",
        AdminOperator,
        "pke_keyset",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/pke/keysets/{name_or_id}",
        AdminOperator,
        "pke_keyset",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/pke/keysets/{name_or_id}/active",
        AdminOperator,
        "pke_keyset",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/pke/keysets/{name_or_id}/export",
        AdminOperator,
        "pke_keyset",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/pke/recipients",
        AuthenticatedWrite,
        "pke",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/pke/verify/{address}",
        AuthenticatedRead,
        "pke",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/provenance/devices",
        TenantObject,
        "provenance",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/provenance/files",
        TenantObject,
        "provenance",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/provenance/locations",
        TenantObject,
        "provenance",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/provenance/named-locations",
        TenantObject,
        "provenance",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/provenance/notes",
        TenantObject,
        "provenance",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/rate-limit/status",
        AuthenticatedRead,
        "rate_limit",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/realtime/twilio/{provider_call_id}",
        PublicWithInlineProof,
        "realtime_provider_callback",
        Hidden,
        NoStore,
    ),
    r(
        "/api/v1/search",
        TenantObject,
        "search",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/search/federated",
        TenantObject,
        "search",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/tags",
        AuthenticatedRead,
        "taxonomy",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/templates",
        TenantObject,
        "template",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/templates/{id}",
        TenantObject,
        "template",
        Authenticated,
        PrivateUserData,
    ),
    r(
        "/api/v1/templates/{id}/instantiate",
        TenantObject,
        "template",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/vision/describe",
        AuthenticatedWrite,
        "ai_execution",
        Authenticated,
        NoStore,
    ),
    r(
        "/api/v1/webhooks",
        AdminOperator,
        "webhook_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/webhooks/incoming",
        AdminOperator,
        "webhook_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/webhooks/incoming/validate",
        PublicWithInlineProof,
        "webhook_receiver",
        Hidden,
        NoStore,
    ),
    r(
        "/api/v1/webhooks/incoming/{slug}",
        PublicWithInlineProof,
        "webhook_receiver",
        Hidden,
        NoStore,
    ),
    r(
        "/api/v1/webhooks/{id}",
        AdminOperator,
        "webhook_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/webhooks/{id}/deliveries",
        AdminOperator,
        "webhook_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/webhooks/{id}/test",
        AdminOperator,
        "webhook_control",
        Operator,
        NoStore,
    ),
    r(
        "/api/v1/ws",
        RealtimeTransport,
        "event_stream",
        Hidden,
        NoStore,
    ),
    r(
        "/asyncapi.yaml",
        Docs,
        "docs_schema",
        DocsPublic,
        PublicStatic,
    ),
    r("/health", Public, "health_probe", DocsPublic, PublicProbe),
    r(
        "/health/live",
        Public,
        "health_probe",
        DocsPublic,
        PublicProbe,
    ),
    r("/oauth/authorize", OAuth, "oauth_flow", DocsPublic, NoStore),
    r(
        "/oauth/introspect",
        OAuth,
        "oauth_flow",
        DocsPublic,
        NoStore,
    ),
    r("/oauth/register", OAuth, "oauth_flow", DocsPublic, NoStore),
    r("/oauth/revoke", OAuth, "oauth_flow", DocsPublic, NoStore),
    r("/oauth/token", OAuth, "oauth_flow", DocsPublic, NoStore),
    r(
        "/openapi.yaml",
        Docs,
        "docs_schema",
        DocsPublic,
        PublicStatic,
    ),
    r("/recording.wav", Public, "test_fixture", Hidden, NoStore),
];

const fn r(
    path: &'static str,
    class: PolicyClass,
    action_family: &'static str,
    docs: DocsExposureClass,
    cache: CacheHeaderClass,
) -> RoutePolicy {
    RoutePolicy {
        path,
        class,
        action_family,
        docs,
        cache,
    }
}

pub fn route_policy_for_path(path: &str) -> Option<&'static RoutePolicy> {
    ROUTE_POLICY_INVENTORY
        .iter()
        .find(|route| route_template_matches(route.path, path))
}

pub fn is_public_without_bearer(path: &str) -> bool {
    path.starts_with("/docs")
        || path.starts_with("/swagger-ui")
        || path.starts_with("/api-docs")
        || route_policy_for_path(path).is_some_and(|policy| {
            matches!(
                policy.class,
                Public | Docs | OAuth | RealtimeTransport | PublicWithInlineProof
            )
        })
}

pub fn is_admin_operator_route(path: &str) -> bool {
    // Transitional #710 slice: the inventory can classify future hosted
    // admin/operator routes, but current scope enforcement remains limited to
    // credential management until the full AuthorizationPolicy middleware lands.
    route_policy_for_path(path).is_some_and(|policy| {
        policy.class == AdminOperator && policy.action_family == "credential_management"
    })
}

fn route_template_matches(template: &str, path: &str) -> bool {
    let mut template_segments = template.split('/');
    let mut path_segments = path.split('/');

    loop {
        match (template_segments.next(), path_segments.next()) {
            (None, None) => return true,
            (Some(t), Some(p)) if is_template_param(t) && !p.is_empty() => {}
            (Some(t), Some(p)) if t == p => {}
            _ => return false,
        }
    }
}

fn is_template_param(segment: &str) -> bool {
    segment.starts_with('{') && segment.ends_with('}')
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn registered_routes_have_policy_inventory_rows() {
        let registered = extract_registered_routes(include_str!("main.rs"));
        let inventoried: BTreeSet<_> = ROUTE_POLICY_INVENTORY
            .iter()
            .map(|route| route.path)
            .collect();

        let missing: Vec<_> = registered.difference(&inventoried).copied().collect();
        assert!(
            missing.is_empty(),
            "routes missing policy inventory rows: {missing:?}"
        );
    }

    #[test]
    fn policy_inventory_paths_are_registered() {
        let registered = extract_registered_routes(include_str!("main.rs"));
        let unregistered: Vec<_> = ROUTE_POLICY_INVENTORY
            .iter()
            .map(|route| route.path)
            .filter(|path| !registered.contains(path))
            .collect();

        assert!(
            unregistered.is_empty(),
            "policy inventory rows without registered routes: {unregistered:?}"
        );
    }

    #[test]
    fn api_key_management_is_one_admin_operator_family() {
        assert!(is_admin_operator_route("/api/v1/api-keys"));
        assert!(is_admin_operator_route(
            "/api/v1/api-keys/018fd1a0-0000-7000-8000-000000000000"
        ));
    }

    #[test]
    fn public_callback_routes_are_not_admin_operator_routes() {
        assert!(is_public_without_bearer(
            "/api/v1/webhooks/incoming/example"
        ));
        assert!(is_public_without_bearer("/api/v1/realtime/twilio/CA123"));
        assert!(!is_admin_operator_route(
            "/api/v1/webhooks/incoming/example"
        ));
    }

    fn extract_registered_routes(source: &'static str) -> BTreeSet<&'static str> {
        let mut routes = BTreeSet::new();
        let mut remaining = source;

        while let Some(route_pos) = remaining.find(".route(") {
            remaining = &remaining[route_pos + ".route(".len()..];
            let Some(first_quote) = remaining.find('"') else {
                continue;
            };
            remaining = &remaining[first_quote + 1..];
            let Some(second_quote) = remaining.find('"') else {
                continue;
            };
            let path = &remaining[..second_quote];
            routes.insert(path);
            remaining = &remaining[second_quote + 1..];
        }

        routes
    }
}
