-- W3C PROV Provenance Tracking for AI Revisions
-- Implements provenance_edge table for tracking the lineage of AI-generated content.
-- Based on W3C PROV-DM (Provenance Data Model) concepts:
--   prov:wasDerivedFrom - content derived from source notes
--   prov:wasGeneratedBy - content generated by AI revision activity
--   prov:used           - AI revision used context from related notes

-- Create provenance_edge table (defined in initial schema but not yet deployed)
CREATE TABLE IF NOT EXISTS provenance_edge (
  id UUID PRIMARY KEY DEFAULT gen_uuid_v7(),
  revision_id UUID REFERENCES note_revision(id) ON DELETE CASCADE,
  source_note_id UUID REFERENCES note(id) ON DELETE SET NULL,
  source_url TEXT,
  relation TEXT NOT NULL,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for efficient provenance queries
CREATE INDEX IF NOT EXISTS idx_provenance_revision ON provenance_edge(revision_id);
CREATE INDEX IF NOT EXISTS idx_provenance_source_note ON provenance_edge(source_note_id);
CREATE INDEX IF NOT EXISTS idx_provenance_relation ON provenance_edge(relation);

-- Activity table for tracking AI processing activities (W3C PROV Activity)
CREATE TABLE IF NOT EXISTS provenance_activity (
  id UUID PRIMARY KEY DEFAULT gen_uuid_v7(),
  note_id UUID NOT NULL REFERENCES note(id) ON DELETE CASCADE,
  revision_id UUID REFERENCES note_revision(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL,  -- 'ai_revision', 'title_generation', 'context_update', 'concept_tagging'
  model_name TEXT,              -- AI model used (e.g., 'gpt-oss:20b')
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  metadata JSONB               -- Additional activity metadata (revision_mode, token counts, etc.)
);

CREATE INDEX IF NOT EXISTS idx_prov_activity_note ON provenance_activity(note_id);
CREATE INDEX IF NOT EXISTS idx_prov_activity_revision ON provenance_activity(revision_id);
CREATE INDEX IF NOT EXISTS idx_prov_activity_type ON provenance_activity(activity_type);

COMMENT ON TABLE provenance_edge IS 'W3C PROV edges tracking derivation lineage of AI-revised content';
COMMENT ON TABLE provenance_activity IS 'W3C PROV activities tracking AI processing operations';
COMMENT ON COLUMN provenance_edge.relation IS 'W3C PROV relation type: wasDerivedFrom, used, wasInformedBy';
COMMENT ON COLUMN provenance_activity.activity_type IS 'Type of AI processing: ai_revision, title_generation, context_update, concept_tagging';
