name: Build Builder Image

on:
  push:
    branches: [main]
    paths:
      - 'build/Dockerfile.builder'
      - 'build/Dockerfile.testdb'
      - 'build/scripts/**'
  # Also build on release tags to publish versioned builder images
  create:
    tags: ['v*']
  workflow_dispatch:

env:
  # GitHub Container Registry (public)
  GHCR_REGISTRY: ghcr.io
  # Gitea Registry (internal)
  GITEA_REGISTRY: git.integrolabs.net
  BUILDER_IMAGE: fortemi/fortemi-builder
  TESTDB_IMAGE: fortemi/fortemi-testdb

jobs:
  build-builder:
    name: Build and Push Builder Image
    runs-on: titan
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 --branch ${GITHUB_REF_NAME:-main} https://token:${{ github.token }}@git.integrolabs.net/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA:-HEAD}

      - name: Log in to registries
        run: |
          echo "${{ secrets.GH_PUBLISH_TOKEN }}" | docker login ${GHCR_REGISTRY} -u fortemi --password-stdin
          echo "${{ secrets.BUILD_REPO_TOKEN }}" | docker login ${GITEA_REGISTRY} -u ${{ gitea.actor }} --password-stdin

      - name: Build builder image
        run: |
          GHCR_IMAGE="${GHCR_REGISTRY}/${BUILDER_IMAGE}"
          GITEA_IMAGE="${GITEA_REGISTRY}/${BUILDER_IMAGE}"
          SHORT_SHA="${GITHUB_SHA:0:7}"
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "Building builder image..."
          docker build \
            -f build/Dockerfile.builder \
            --build-arg BUILD_DATE=${BUILD_DATE} \
            -t ${GHCR_IMAGE}:latest \
            -t ${GHCR_IMAGE}:sha-${SHORT_SHA} \
            -t ${GITEA_IMAGE}:latest \
            -t ${GITEA_IMAGE}:sha-${SHORT_SHA} \
            .

          # Add version tag if this is a release
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
            echo "Adding version tag: ${VERSION}"
            docker tag ${GHCR_IMAGE}:latest ${GHCR_IMAGE}:${VERSION}
            docker tag ${GITEA_IMAGE}:latest ${GITEA_IMAGE}:${VERSION}
          fi

      - name: Build testdb image
        run: |
          GHCR_IMAGE="${GHCR_REGISTRY}/${TESTDB_IMAGE}"
          GITEA_IMAGE="${GITEA_REGISTRY}/${TESTDB_IMAGE}"
          SHORT_SHA="${GITHUB_SHA:0:7}"

          echo "Building testdb image (pgvector + PostGIS)..."
          docker build \
            -f build/Dockerfile.testdb \
            -t ${GHCR_IMAGE}:latest \
            -t ${GHCR_IMAGE}:sha-${SHORT_SHA} \
            -t ${GITEA_IMAGE}:latest \
            -t ${GITEA_IMAGE}:sha-${SHORT_SHA} \
            .

          # Add version tag if this is a release
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
            echo "Adding version tag: ${VERSION}"
            docker tag ${GHCR_IMAGE}:latest ${GHCR_IMAGE}:${VERSION}
            docker tag ${GITEA_IMAGE}:latest ${GITEA_IMAGE}:${VERSION}
          fi

      - name: Test builder image
        run: |
          IMAGE="${GHCR_REGISTRY}/${BUILDER_IMAGE}"

          echo "Testing builder image..."

          # Test Rust toolchain
          docker run --rm ${IMAGE}:latest rustc --version
          docker run --rm ${IMAGE}:latest cargo --version

          # Test components
          docker run --rm ${IMAGE}:latest cargo fmt --version
          docker run --rm ${IMAGE}:latest cargo clippy --version

          # Test sqlx
          docker run --rm ${IMAGE}:latest sqlx --version

          # Test Node.js
          docker run --rm ${IMAGE}:latest node --version
          docker run --rm ${IMAGE}:latest npm --version

          # Test Docker CLI
          docker run --rm ${IMAGE}:latest docker --version

          echo "All builder tests passed!"

      - name: Test testdb image
        run: |
          IMAGE="${GHCR_REGISTRY}/${TESTDB_IMAGE}"

          echo "Testing testdb image..."

          # Start container and verify extensions
          docker run -d --name testdb-verify \
            -e POSTGRES_PASSWORD=test \
            ${IMAGE}:latest

          # Wait for PostgreSQL
          for i in {1..30}; do
            if docker exec testdb-verify pg_isready -U postgres 2>/dev/null; then
              break
            fi
            sleep 1
          done

          # Verify pgvector extension
          docker exec testdb-verify psql -U postgres -c "CREATE EXTENSION IF NOT EXISTS vector;"
          echo "pgvector: OK"

          # Verify PostGIS extension
          docker exec testdb-verify psql -U postgres -c "CREATE EXTENSION IF NOT EXISTS postgis;"
          echo "PostGIS: OK"

          # Cleanup
          docker stop testdb-verify
          docker rm testdb-verify

          echo "All testdb tests passed!"

      - name: Push images
        run: |
          SHORT_SHA="${GITHUB_SHA:0:7}"

          # Retry function for transient registry errors
          push_with_retry() {
            local image=$1
            local max_attempts=3
            local attempt=1
            while [ $attempt -le $max_attempts ]; do
              echo "Pushing ${image} (attempt ${attempt}/${max_attempts})..."
              if docker push "${image}"; then
                return 0
              fi
              echo "Push failed, waiting before retry..."
              sleep $((attempt * 5))
              attempt=$((attempt + 1))
            done
            echo "Failed to push ${image} after ${max_attempts} attempts"
            return 1
          }

          # Push to GitHub Container Registry
          GHCR_BUILDER="${GHCR_REGISTRY}/${BUILDER_IMAGE}"
          GHCR_TESTDB="${GHCR_REGISTRY}/${TESTDB_IMAGE}"

          echo "Pushing to GitHub Container Registry..."
          push_with_retry ${GHCR_BUILDER}:latest
          push_with_retry ${GHCR_BUILDER}:sha-${SHORT_SHA}
          push_with_retry ${GHCR_TESTDB}:latest
          push_with_retry ${GHCR_TESTDB}:sha-${SHORT_SHA}

          # Push to Gitea Registry
          GITEA_BUILDER="${GITEA_REGISTRY}/${BUILDER_IMAGE}"
          GITEA_TESTDB="${GITEA_REGISTRY}/${TESTDB_IMAGE}"

          echo "Pushing to Gitea Registry..."
          push_with_retry ${GITEA_BUILDER}:latest
          push_with_retry ${GITEA_BUILDER}:sha-${SHORT_SHA}
          push_with_retry ${GITEA_TESTDB}:latest
          push_with_retry ${GITEA_TESTDB}:sha-${SHORT_SHA}

          # Push version tags if this is a release
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
            echo "Pushing version-tagged images: ${VERSION}"
            push_with_retry ${GHCR_BUILDER}:${VERSION}
            push_with_retry ${GHCR_TESTDB}:${VERSION}
            push_with_retry ${GITEA_BUILDER}:${VERSION}
            push_with_retry ${GITEA_TESTDB}:${VERSION}
          fi

          echo "Published images:"
          echo "  GitHub (ghcr.io):"
          echo "    - ${GHCR_BUILDER}:latest, :sha-${SHORT_SHA}"
          echo "    - ${GHCR_TESTDB}:latest, :sha-${SHORT_SHA}"
          echo "  Gitea:"
          echo "    - ${GITEA_BUILDER}:latest, :sha-${SHORT_SHA}"
          echo "    - ${GITEA_TESTDB}:latest, :sha-${SHORT_SHA}"

  # After builder is published, trigger CI to validate with new image
  trigger-ci:
    name: Trigger CI with New Builder
    runs-on: titan
    needs: build-builder
    steps:
      - name: Trigger CI workflows
        run: |
          echo "Triggering CI workflows to use new builder image..."

          # Trigger ci-builder.yaml via workflow_dispatch
          curl -X POST \
            -H "Authorization: token ${{ secrets.BUILD_REPO_TOKEN }}" \
            -H "Accept: application/json" \
            "https://git.integrolabs.net/api/v1/repos/${GITHUB_REPOSITORY}/actions/workflows/ci-builder.yaml/dispatches" \
            -d '{"ref":"main"}' || echo "Dispatch may not be supported, CI will run on next push"

          # Also trigger ci.yaml
          curl -X POST \
            -H "Authorization: token ${{ secrets.BUILD_REPO_TOKEN }}" \
            -H "Accept: application/json" \
            "https://git.integrolabs.net/api/v1/repos/${GITHUB_REPOSITORY}/actions/workflows/ci.yaml/dispatches" \
            -d '{"ref":"main"}' || echo "Dispatch may not be supported, CI will run on next push"

          echo "CI workflows triggered (or will run on next code push)"
