# Vault CI fetch spec for workflows that publish container images.
env GH_PUBLISH_TOKEN ${GH_PUBLISH_TOKEN_VAULT_PATH} ${GH_PUBLISH_TOKEN_VAULT_FIELD}
env BUILD_REPO_TOKEN ${BUILD_REPO_TOKEN_VAULT_PATH} ${BUILD_REPO_TOKEN_VAULT_FIELD}
