# Vault CI fetch spec for .gitea/workflows/build-pyannote.yaml.
env GH_PUBLISH_TOKEN ${GH_PUBLISH_TOKEN_VAULT_PATH} ${GH_PUBLISH_TOKEN_VAULT_FIELD}
env BUILD_REPO_TOKEN ${BUILD_REPO_TOKEN_VAULT_PATH} ${BUILD_REPO_TOKEN_VAULT_FIELD}
env HF_TOKEN ${HF_TOKEN_VAULT_PATH} ${HF_TOKEN_VAULT_FIELD}
