# Vault CI fetch spec for .gitea/workflows/docsite-deploy.yml.
keyfile DEPLOY_SSH_KEY_FILE ${DEPLOY_SSH_KEY_VAULT_PATH} ${DEPLOY_SSH_KEY_VAULT_FIELD}
env CLOUDFLARE_API_TOKEN ${CLOUDFLARE_API_TOKEN_VAULT_PATH} ${CLOUDFLARE_API_TOKEN_VAULT_FIELD}
