#!/usr/bin/env bash
set -euo pipefail
umask 077

# Generate .env configuration for Fortémi Docker bundle
# Params: INSTALL_DIR, DOMAIN, PROTOCOL, COMPOSE_PROFILES, INFERENCE_PROVIDER,
#         OLLAMA_GEN_MODEL, OLLAMA_EMBED_MODEL, OPENAI_API_KEY,
#         OPENROUTER_API_KEY, LLAMACPP_BASE_URL, DATA_DIR,
#         FORTEMI_INSTALL_MODE, FORTEMI_EXPOSURE_PROFILE

INSTALL_DIR="${INSTALL_DIR:?INSTALL_DIR is required}"
DOMAIN="${DOMAIN:-localhost}"
COMPOSE_PROFILES="${COMPOSE_PROFILES:-edge}"
INFERENCE_PROVIDER="${INFERENCE_PROVIDER:-ollama}"
OLLAMA_GEN_MODEL="${OLLAMA_GEN_MODEL:-qwen3.5:9b}"
OLLAMA_EMBED_MODEL="${OLLAMA_EMBED_MODEL:-nomic-embed-text}"
DATA_DIR="${DATA_DIR:-${INSTALL_DIR}/data}"
FORTEMI_INSTALL_MODE="${FORTEMI_INSTALL_MODE:-secure}"
FORTEMI_EXPOSURE_PROFILE="${FORTEMI_EXPOSURE_PROFILE:-local}"

case "${FORTEMI_INSTALL_MODE}" in
    secure)
        REQUIRE_AUTH_VALUE=true
        I_UNDERSTAND_NO_AUTH_VALUE=false
        HOST_VALUE="${HOST:-0.0.0.0}"
        ;;
    local-no-auth)
        REQUIRE_AUTH_VALUE=false
        I_UNDERSTAND_NO_AUTH_VALUE=true
        HOST_VALUE="${HOST:-0.0.0.0}"
        ;;
    *)
        echo "ERROR: FORTEMI_INSTALL_MODE must be 'secure' or 'local-no-auth'."
        echo "  secure        require authentication and allow normal host binding"
        echo "  local-no-auth generate the explicit no-auth acknowledgment and bind to 127.0.0.1"
        exit 1
        ;;
esac

case "${FORTEMI_EXPOSURE_PROFILE}" in
    local)
        API_HOST_BIND_VALUE="${API_HOST_BIND:-127.0.0.1}"
        MCP_HOST_BIND_VALUE="${MCP_HOST_BIND:-127.0.0.1}"
        ;;
    shared)
        if [ "${FORTEMI_INSTALL_MODE}" != "secure" ]; then
            echo "ERROR: shared exposure requires FORTEMI_INSTALL_MODE=secure."
            exit 1
        fi
        : "${POSTGRES_PASSWORD:?shared exposure requires POSTGRES_PASSWORD}"
        : "${ALLOWED_ORIGINS:?shared exposure requires ALLOWED_ORIGINS}"
        : "${MCP_BASE_URL:?shared exposure requires MCP_BASE_URL}"
        API_HOST_BIND_VALUE="${API_HOST_BIND:-0.0.0.0}"
        MCP_HOST_BIND_VALUE="${MCP_HOST_BIND:-0.0.0.0}"
        ;;
    *)
        echo "ERROR: FORTEMI_EXPOSURE_PROFILE must be 'local' or 'shared'."
        exit 1
        ;;
esac
API_HOST_PORT_VALUE="${API_HOST_PORT:-3000}"
MCP_HOST_PORT_VALUE="${MCP_HOST_PORT:-3001}"

# Smart protocol default: http for localhost, https otherwise
if [ -z "${PROTOCOL:-}" ]; then
    if echo "${DOMAIN}" | grep -qE '^(localhost|127\.0\.0\.1)'; then
        PROTOCOL="http"
    else
        PROTOCOL="https"
    fi
fi

ENV_FILE="${INSTALL_DIR}/.env"

if [ -f "${ENV_FILE}" ]; then
    echo "Existing .env found — backing up to .env.bak"
    cp "${ENV_FILE}" "${ENV_FILE}.bak"
fi

# Create data directories
if ! mkdir -p "${DATA_DIR}/postgres" "${DATA_DIR}/redis" "${DATA_DIR}/uploads" 2>/dev/null; then
    echo "ERROR: Cannot create ${DATA_DIR} — permission denied."
    echo "Either run as root, or set DATA_DIR to a writable path:"
    echo "  DATA_DIR=~/fortemi-data aiwg setup-run"
    exit 1
fi

cat > "${ENV_FILE}" <<EOF
# Fortémi Configuration — generated by setup manifest
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Domain and protocol (${PROTOCOL}://${DOMAIN})
ISSUER_URL=${PROTOCOL}://${DOMAIN}

# Hardware profile: edge | gpu-12gb | gpu-24gb
COMPOSE_PROFILES=${COMPOSE_PROFILES}

# Install mode: secure | local-no-auth
FORTEMI_INSTALL_MODE=${FORTEMI_INSTALL_MODE}

# Exposure profile: local | shared
FORTEMI_EXPOSURE_PROFILE=${FORTEMI_EXPOSURE_PROFILE}

# Inference provider: ollama | openai | openrouter | llamacpp
MATRIC_INFERENCE_DEFAULT=${INFERENCE_PROVIDER}

# Data persistence
PGDATA=${DATA_DIR}/postgres
REDIS_DATA=${DATA_DIR}/redis
UPLOAD_DIR=${DATA_DIR}/uploads

# Authentication (ADR-094: fail-closed default, fortemi/fortemi#709).
# Authentication is required by default. local-no-auth is only for local
# single-user workstation installs and intentionally binds published ports
# to 127.0.0.1.
REQUIRE_AUTH=${REQUIRE_AUTH_VALUE}
I_UNDERSTAND_NO_AUTH=${I_UNDERSTAND_NO_AUTH_VALUE}
HOST=${HOST_VALUE}
API_HOST_BIND=${API_HOST_BIND_VALUE}
MCP_HOST_BIND=${MCP_HOST_BIND_VALUE}
API_HOST_PORT=${API_HOST_PORT_VALUE}
MCP_HOST_PORT=${MCP_HOST_PORT_VALUE}
EOF

if [ "${FORTEMI_EXPOSURE_PROFILE}" = "shared" ]; then
    cat >> "${ENV_FILE}" <<EOF
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
MCP_BASE_URL=${MCP_BASE_URL}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
EOF
fi

# Append provider-specific configuration
case "${INFERENCE_PROVIDER}" in
    ollama)
        cat >> "${ENV_FILE}" <<EOF

# Ollama (local inference — runs on the host, not in Docker)
OLLAMA_GEN_MODEL=${OLLAMA_GEN_MODEL}
OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL}
EOF
        ;;
    openai)
        cat >> "${ENV_FILE}" <<EOF

# OpenAI (cloud inference — no local GPU required)
OPENAI_API_KEY=${OPENAI_API_KEY:-}
# OPENAI_BASE_URL=https://api.openai.com/v1
# OPENAI_GEN_MODEL=gpt-4o-mini
# OPENAI_EMBED_MODEL=text-embedding-3-small
EOF
        ;;
    openrouter)
        cat >> "${ENV_FILE}" <<EOF

# OpenRouter (cloud gateway — 100+ models via a single API)
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
# OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
EOF
        ;;
    llamacpp)
        cat >> "${ENV_FILE}" <<EOF

# llama.cpp (local HTTP server with OpenAI-compatible protocol)
LLAMACPP_BASE_URL=${LLAMACPP_BASE_URL:-http://127.0.0.1:8080}
# LLAMACPP_API_KEY=
EOF
        ;;
esac

echo "Configuration written to ${ENV_FILE}"
echo "  URL:      ${PROTOCOL}://${DOMAIN}"
echo "  Profile:  ${COMPOSE_PROFILES}"
echo "  Provider: ${INFERENCE_PROVIDER}"
echo "  Mode:     ${FORTEMI_INSTALL_MODE}"
echo "  Exposure: ${FORTEMI_EXPOSURE_PROFILE}"
echo "  API bind: ${API_HOST_BIND_VALUE}:${API_HOST_PORT_VALUE}"
echo "  MCP bind: ${MCP_HOST_BIND_VALUE}:${MCP_HOST_PORT_VALUE}"
if [ "${FORTEMI_INSTALL_MODE}" = "local-no-auth" ]; then
    echo "  Auth:     disabled intentionally; host ports bound to 127.0.0.1"
else
    echo "  Auth:     required"
fi
if [ "${FORTEMI_EXPOSURE_PROFILE}" = "shared" ]; then
    echo "  WARNING: non-loopback exposure selected; deploy preflight will require"
    echo "           public HTTPS metadata/origins and a non-default DB secret."
fi
if [ "${INFERENCE_PROVIDER}" = "ollama" ]; then
    echo "  Model:    ${OLLAMA_GEN_MODEL}"
fi
echo "  Data dir: ${DATA_DIR}"
