#!/usr/bin/env bash
set -euo pipefail

# Generate .env configuration for Fortémi Docker bundle
# Params: INSTALL_DIR, DOMAIN, PROTOCOL, COMPOSE_PROFILES, OLLAMA_GEN_MODEL, DATA_DIR

INSTALL_DIR="${INSTALL_DIR:?INSTALL_DIR is required}"
DOMAIN="${DOMAIN:-localhost}"
COMPOSE_PROFILES="${COMPOSE_PROFILES:-edge}"
OLLAMA_GEN_MODEL="${OLLAMA_GEN_MODEL:-qwen3.5:9b}"
DATA_DIR="${DATA_DIR:-${INSTALL_DIR}/data}"

# Smart protocol default: http for localhost, https otherwise
if [ -z "${PROTOCOL:-}" ]; then
    if echo "${DOMAIN}" | grep -qE '^(localhost|127\.0\.0\.1)'; then
        PROTOCOL="http"
    else
        PROTOCOL="https"
    fi
fi

ENV_FILE="${INSTALL_DIR}/.env"

if [ -f "${ENV_FILE}" ]; then
    echo "Existing .env found — backing up to .env.bak"
    cp "${ENV_FILE}" "${ENV_FILE}.bak"
fi

# Create data directories
if ! mkdir -p "${DATA_DIR}/postgres" "${DATA_DIR}/redis" "${DATA_DIR}/uploads" "${DATA_DIR}/ollama" 2>/dev/null; then
    echo "ERROR: Cannot create ${DATA_DIR} — permission denied."
    echo "Either run as root, or set DATA_DIR to a writable path:"
    echo "  DATA_DIR=~/fortemi-data aiwg setup-run"
    exit 1
fi

cat > "${ENV_FILE}" <<EOF
# Fortémi Configuration — generated by setup manifest
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Domain and protocol (${PROTOCOL}://${DOMAIN})
ISSUER_URL=${PROTOCOL}://${DOMAIN}

# Hardware profile: edge | gpu-12gb | gpu-24gb
COMPOSE_PROFILES=${COMPOSE_PROFILES}

# Generation + vision model
OLLAMA_GEN_MODEL=${OLLAMA_GEN_MODEL}

# Data persistence
PGDATA=${DATA_DIR}/postgres
REDIS_DATA=${DATA_DIR}/redis
UPLOAD_DIR=${DATA_DIR}/uploads
OLLAMA_DATA=${DATA_DIR}/ollama

# Authentication (default: open — enable after registering clients)
REQUIRE_AUTH=false
EOF

echo "Configuration written to ${ENV_FILE}"
echo "  URL:      ${PROTOCOL}://${DOMAIN}"
echo "  Profile:  ${COMPOSE_PROFILES}"
echo "  Model:    ${OLLAMA_GEN_MODEL}"
echo "  Data dir: ${DATA_DIR}"
